# Generated by Django 2.2.3 on 2019-09-02 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='预约日期')),
                ('tb_id', models.SmallIntegerField(verbose_name='预约时段')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.UserInfo')),
            ],
            options={
                'db_table': 'tb_reservationinfo',
                'verbose_name_plural': '预约信息表',
                'verbose_name': '预约信息表',
            },
        ),
    ]
