# Generated by Django 2.2.5 on 2019-09-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('infos', '0003_auto_20190905_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewinfo',
            name='num',
            field=models.SmallIntegerField(default=10),
        ),
        migrations.RemoveField(
            model_name='interviewinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='interviewinfo',
            name='user',
            field=models.ManyToManyField(to='users.UserInfo'),
        ),
    ]
