# Generated by Django 2.2.5 on 2019-09-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0006_auto_20190910_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewinfo',
            name='comment',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='备注说明(选填)'),
        ),
        migrations.AlterField(
            model_name='interviewinfo',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to='users.UserInfo', verbose_name='预约学生(选填)'),
        ),
    ]
