# Generated by Django 2.2.3 on 2019-09-11 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0007_auto_20190910_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewinfo',
            name='num',
            field=models.SmallIntegerField(default=6, verbose_name='可预约人数'),
        ),
        migrations.AlterField(
            model_name='reservationinfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.UserInfo'),
        ),
    ]
