# Generated by Django 2.2.3 on 2019-09-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0008_auto_20190911_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewinfo',
            name='tb_id',
            field=models.SmallIntegerField(choices=[(1, '上午'), (2, '下午'), (3, '晚上')], verbose_name='开放面试时段'),
        ),
    ]
