# Generated by Django 2.2.3 on 2019-09-17 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # ('experiments', '0001_initial'),
        ('infos', '0009_auto_20190912_1420'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='reservationinfo',
        #     name='lab_adress',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experiments.LabAdress'),
        # ),
        migrations.AlterField(
            model_name='interviewinfo',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='备注说明(选填)'),
        ),
    ]
