# Generated by Django 2.2.3 on 2019-09-17 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experiments', '0002_remove_labadress_rockname'),
        ('infos', '0010_auto_20190917_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationinfo',
            name='lab_adress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experiments.LabAdress'),
        ),
    ]
