# Generated by Django 2.2.3 on 2019-09-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursedate_courseschedule_teacherinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseschedule',
            name='comment',
            field=models.CharField(blank=True, max_length=60, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='coursedate',
            name='opendate',
            field=models.SmallIntegerField(choices=[(1, '否'), (2, '是')], default=1, verbose_name='是否为开课日期'),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='schooltime',
            field=models.CharField(max_length=40, verbose_name='上课时间'),
        ),
    ]
