# Generated by Django 2.2.3 on 2019-09-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='adress',
            field=models.CharField(default='', max_length=30, verbose_name='学校/企业名称'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(default='', max_length=11, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='qq',
            field=models.CharField(default='', max_length=11, verbose_name='QQ'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='realname',
            field=models.CharField(default='', max_length=20, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.CharField(default='', max_length=50, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=12, unique=True, verbose_name='用户名'),
        ),
    ]
